### ISSUE TITLE
Migrate project to 'path'

### ISSUE THREAD

**Issue by jaraco** [jaraco/path#169]
After some time, I've managed to get the name 'path' on PyPI (pypa/warehouse#4123). I'd like to publish this package there (and deprecate this one).

**Comment by SethMMorton** [comment]
The only draw back to this might be that finding the project through a google search may become more challenging. If I search for "python path", I end up getting results for `PYTHONPATH`. If I search "python path.py" I at least get *some* hits for this module.

Not saying that this is a bad idea (I like it) but it is something to keep in mind.

**Comment by jaraco** [comment]
That's a really good point. I wonder if there's an additional moniker that could make it easier to find it. Maybe "path package" or "path tool" or maybe a codename like "path pie" :).

**Comment by jaraco** [comment]
I kinda like the 'path pie' idea (borrows from CherryPy and raspberry pi and httpie). It would be an unofficial, pet name to easier discovery. In #177, I've drafted that change.

**Comment by jaraco** [comment]
Released as [path 13](https://pypi.org/project/path).

**Comment by SethMMorton** [comment]
What mechanism do you have to notify users of this change?

**Comment by jaraco** [comment]
My intention is to cut a release of path.py whose read me directs users to this new name. GitHub automatically redirects from the old name. I think that’s enough. Can you foresee any problems with that.

**Comment by SethMMorton** [comment]
I am thinking about project owners that are just including `path.py` (no version) as a `install_requires` for their library (or the analogous situation for an application owner).  Most project owners do not check on the status of projects they depend on unless there is a bug. So I am foreseeing the following situations:

- Code that is currently depending on `path.py` will never update the dependency to be `path` because `path.py` is a great library as-is and is unlikely to be the cause of bugs. So, this code may not get the benefit of improvements made to `path`. This may make full migration to `path` slow or not possible, which will be frustrating.
- Due to the above, I can imagine a user installing a library that depends on `path.py` and also one that depends on `path`. Because `path.py` and `path` are using the same namespace, there will be a conflict.
   - I would hope, that this would be detected by `pip` at install time... If so, it would (should?) lead to installation conflicts unless of course `pip` is able to know somehow that `path.py` got renamed to `path` and can handle the change gracefully. If it does lead to installation conflicts, I can imagine pitchforks...

I think that all of the above concerns would be moot if `pip` is able to understand that `path` == `path.py`, so if someone says `pip install path.py==13.0.0` they would end up getting `path` version 13... but I don't think that capability exists.

Do you plan on throwing a deprecation message in `path.py`? Or is there a way for `pip` to issue a warning at installation time that `path.py` is now `path`?

**Comment by jaraco** [comment]
Unfortunately, pip doesn't detect conflicts. It happily installs one over the other. The biggest danger happens as the two projects diverge (especially if older path.py overrides newer path) or if one of the packages is uninstalled:

```
draft $ python -m venv conflict                                                                                                                                           
draft $ conflict/bin/pip install path path.py                                                                                                                             
Collecting path
  Using cached https://files.pythonhosted.org/packages/7c/d3/19effb6328caed6cd54faa0a56c80346a8bdb5fa207c6ff18ff803ddc883/path-13.0.0-py3-none-any.whl
Collecting path.py
  Using cached https://files.pythonhosted.org/packages/9e/9d/2af32e7a3e332eba991f964ebd1d3f1aa45097f00698eb8c2ccb43431be0/path.py-12.2.0-py3-none-any.whl
Installing collected packages: path, path.py
Successfully installed path-13.0.0 path.py-12.2.0
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
draft $ conflict/bin/pip uninstall path.py                                                                                                                                
Uninstalling path.py-12.2.0:
  Would remove:
    /Users/jaraco/draft/conflict/lib/python3.8/site-packages/path.py-12.2.0.dist-info/*
    /Users/jaraco/draft/conflict/lib/python3.8/site-packages/path/*
Proceed (y/n)? y
  Successfully uninstalled path.py-12.2.0
draft $ conflict/bin/python -c "import path"                                                                                                                              
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'path'
```

Yes, I think a deprecation warning in `path.py` is appropriate.

**Comment by jaraco** [comment]
In a0fba60, I've added a DeprecationWarning (to the maintenance branch, not yet released).

**Comment by jaraco** [comment]
For background, the [packaging ecosystem doesn't have support for obsoleting a package](https://github.com/pypa/packaging-problems/issues/154).

**Comment by jaraco** [comment]
Given all of this, I'm inclined to put a moratorium on changes for this project (except security and bug fixes) for a period of 6 months so there's a stable overlap of the deprecated and superseding packages, and any changes applied to the latest path.py should apply to the latest path.

**Comment by jaraco** [comment]
Hmm. It occurs to me it may be possible to simply replace `path.py` with an empty package that depends on `path`. Yes, I think that would be preferable.

**Comment by jaraco** [comment]
In 5564d7c, I've drafted that approach.

**Comment by SethMMorton** [comment]
I think this will be good going forward. But I don't think it will help the case where someone installs `path.py` version 11 (for example) and `path`.  There's probably nothing that can be done in that case, correct?

**Comment by jaraco** [comment]
There's very little one could do in that case. I suppose one or both packages could install a hook that checks the package metadata to ensure that both `path` and `path.py` aren't "installed" (both have metadata present), and warn if so. I guess that would only need to be present on the newer `path` package. Is it worth the effort and cost? My instinct is no.

**Comment by jaraco** [comment]
There's very little one could do in that case. I suppose one or both packages could install a hook that checks the package metadata to ensure that both `path` and `path.py` aren't "installed" (both have metadata present), and warn if so. I guess that would only need to be present on the newer `path` package. Is it worth the effort and cost? My instinct is no.

**Comment by jaraco** [comment]
I've re-opened the issue until the final path.py is released.

**Comment by jaraco** [comment]
I've tagged 5564d7c as `v12.3.0`, which should cause that to be released as `path.py 12.3`.

**Comment by jaraco** [comment]
> Is it worth the effort and cost? My instinct is no.

If something indicates that it's worth the effort or if someone wishes to volunteer the effort, I'm open to a PR.
