### ISSUE TITLE
no read_text in path.py

### ISSUE THREAD

**Issue by gsemet** [jaraco/path#170]
Hi.
I though path.Path was acting like a children of `pathlib.Path`, so that they can be converted easily, but I see `path.Path` does not have some methods such as `read_text`. Is it necessary to convert to `pathlib.Path` in order to use `read_text`?

Thanks

**Comment by jaraco** [comment]
Hi gsemet. The `path.py` project has been around since [at least 2003](https://pypi.org/project/path.py/1.2/), whereas `pathlib` was new in Python 3.4, so you can expect to find variance in the implementations.

That said, this project has a stated goal to align as much as possible with pathlib such that users of pathlib might be able to opt-in to path.py to take advantage of its [unique features](https://github.com/jaraco/path.py#advantages).

To that end, if you or anyone would like to add the functionality (and deprecate any interfaces that are superseded), please do put together a PR.

**Comment by gsemet** [comment]
waouh, didn't know it was so old :) I clearly prefer `path.py` even if `pathlib` is fine. Will see if I find time to add this PR :)
