### ISSUE TITLE
lines() is implemented using text(), not read_text()

### ISSUE THREAD

**Issue by SethMMorton** [jaraco/path#187]
The `text()` function now has a deprecation warning telling  users to use `read_text()` instead. However, `lines()` is implemented using `text()`, not `read_text()`, so I cannot get rid of my deprecation warnings if I wish to use `lines()`.

It looks like this was introduced in 5c93ac90dace92cb2815d16d7ee87cfa8a4b6531 for #170. 

As a side note, should `lines()` become `read_lines()` for symmetry?

**Comment by jaraco** [comment]
Wow. <insert self-deprecating humor>

I'm a little surprised the deprecation warnings aren't raised during tests. I wonder if that means `lines()` isn't tested.

> should `lines()` become `read_lines()` for symmetry?

Perhaps. The reason `text()` was changed to `read_text()` was to align with pathlib. If pathlib doesn't supply something like `lines` then I'd say just leave it, because pathlib might some day add support for something similar and I'd like to reserve API changes for aligning with pathlib.

**Comment by SethMMorton** [comment]
Interesting - I see these deprecation warnings from `pytest`, and they are on by default.  It looks like yours are being swallowed because of the contents of your `pytest.ini`:

```ini
[pytest]
norecursedirs=dist build .tox .eggs
addopts=--doctest-modules --flake8 --black --cov --mypy
doctest_optionflags=ALLOW_UNICODE ELLIPSIS
# workaround for warning pytest-dev/pytest#6178
junit_family=xunit2
filterwarnings=
    # https://github.com/pytest-dev/pytest/issues/6928
    ignore:direct construction of .*Item has been deprecated:DeprecationWarning
```

I have no issue with keeping `lines()` the same. I was just suggesting for API "beauty" :)

**Comment by SethMMorton** [comment]
Oh wait... maybe not... It looks like your warnings don't match the filter. Huh.

**Comment by jaraco** [comment]
I found [the reason](https://github.com/jaraco/path/blob/4686eae1323dd39561a63b0efe345289d4c0e56e/test_path.py#L575).

**Comment by SethMMorton** [comment]
@jaraco Out of curiosity - in the fix for the warnings, why not change the call from `.text()` to `.read_text()` so that no warning filtering has to be done at all?

**Comment by jaraco** [comment]
I guess I'd like not to support multiple methods that do essentially the same thing. And since the guidance indicates to wrap the call in a normalizing function if the previous behavior is needed, I think most users will not need the old `.text` behavior and the few that do can achieve that with composition rather than redundant endpoints.

**Comment by SethMMorton** [comment]
Ah - I did not fully internalize that `.text()` was doing extra work that was not done by `.read_text()`.
