### ISSUE TITLE
TempDir directory not deleted on interruption

### ISSUE THREAD

**Issue by floriandeboissieu** [jaraco/path#200]
The temporary directory is not deleted on interruption, though it would nice to have this capacity
```
from path import Path, TempDir
from time import sleep
# tmpdir is not deleted when interrupted
with TempDir() as tmpdir:
  print(tmpdir)
  sleep(100) # interrupt before end of sleep
tmpdir.exists() # True

from tempfile import TemporaryDirectory
with TemporaryDirectory() as tmpdir:
  print(tmpdir)
  sleep(100)
Path(tmpdir).exists() # False
```

**Comment by jaraco** [comment]
In https://github.com/jaraco/path/tree/feature/tempdir-cleanup-on-exception, I started experimenting with a solution. But I quickly discovered the test suite is already [capturing the opposite expectation](https://github.com/jaraco/path/blob/8f5adebcaf9b43c765835a9d391bb5ca65d3a67f/test_path.py#L913-L922) - that is, that the temp directory should be left behind if an exception occurs.

I don't recall why that behavior was intentional or not. Looking back at bf82b390a3df6d77370f9470816a93760ca3ca28, it seems that behavior was just some initial implementation.

I think I agree with you that an unconditional cleanup would be preferable. It'll demand a backward-incompatible change.
