### ISSUE TITLE
Add method to see the setted permissions

### ISSUE THREAD

**Issue by Sclafus** [jaraco/path#211]
With `path` you can set file permissions with the `chmod` method, but you can't "get it back" without using the `os` module.

Example usage:
```python
from path import Path
p = Path('example_file')
p.chmod(0o777)

do_stuff()
...

# how to get the permissions from file p?
import os
permission = os.stat(p).st_mode & 0o777 # permissions = 438
print(f"permissions = {oct(permission)}") # permissions = '0o666'

# possible implementation
permission = p.st_mode() # permissions = 438
permission_oct = p.st_mode(oct_str = True) # permission_oct = '0o666'
```
I think this would be a nice addition to the project.

**Comment by Sclafus** [comment]
Just found out you can do `p.stat().st_mode` 😅
Still, i think this would be a nice convenience method.

**Comment by jaraco** [comment]
> it does not do the `&` operation

It seems it does for me:

```
>>> import path
>>> p = path.Path('.')
>>> p.stat().st_mode & 0o777
493
```

Since that's the interface exposed by pathlib, it's probably adequate.

I do find it slightly annoying that one has to indicate 'stat' twice (`.stat()` and `.st_`), but that's a Python wart. We could polish it by providing a `Path.mode` and maybe even wrap the numeric result in something that could render nicely, something like:

```
>>> p.mode
438
>>> oct(p.mode)
'0o666'
>>> str(p.mode) #  or p.mode.symbolic
'rw-rw-rw-'
```

**Comment by Sclafus** [comment]
Hi @jaraco, 
the interface you proposed is very nice, but I may say that `mode` feels a bit cryptic. Perhaps `permission` would be better suited for this library, which is more focused on usability and readability?

**Comment by jaraco** [comment]
At first, I was reluctant, because the underlying name was "mode", so that's what programmers would have expected, historically. However, searching for "unix mode", most of the articles, including the [Wikipedia entry](https://en.wikipedia.org/wiki/File-system_permissions), prefer the term `permissions`. Today, I learned "mode" is shorthand for "access modes". I agree `permissions` (plural) would provide a better user experience.
